import Header from "./components/header";
import Announcementbar from "./components/announcemen-bar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="h-full bg-white" lang="en">
      <body className={'h-full ' + (inter.className)}>
        <Header />
        <Announcementbar />
        {children}
      </body>
    </html>
  );
}
